baseURL = 'https://ifuon.github.io/iFuon/'
languageCode = 'en-us'
title = 'Kangyue'
theme = "anatole"

[params]
title = "I'm Kangyue"
author = "iFuon"
description = "Blockchain, Decentralized, Finance"
profilePicture = "images/me.jpg"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/iFuon"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/kangyue-fu/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:kafu3550@uni.sydney.edu.au"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

 